workflows:
  android-build:
    name: WintoneCloud Android Build
    max_build_duration: 35
    environment:
      flutter: stable
      vars:
        PROJECT_ROOT: "."   # Bu satır yardımcı olur
    scripts:
      - name: Flutter Pub Get
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
